/* ES40 emulator.
 * Copyright (C) 2007-2008 by the ES40 Emulator Project
 *
 * WWW    : http://www.es40.org
 * E-mail : camiel@es40.org
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
 * USA.
 *
 * Although this is not required, the author would appreciate being notified of,
 * and receiving any modifications you may make to the source code that might
 * serve the general public.
 *
 * Parts of this file based upon the Poco C++ Libraries, which is Copyright (C)
 * 2004-2006, Applied Informatics Software Engineering GmbH. and Contributors.
 */

/**
 * $Id: AutoPtr.h,v 1.1 2008/05/31 15:47:19 iamcamiel Exp $
 *
 * X-1.1        Camiel Vanderhoeven                             31-MAY-2008
 *      Initial version for ES40 emulator.
 **/

//
// AutoPtr.h
//
// $Id: AutoPtr.h,v 1.1 2008/05/31 15:47:19 iamcamiel Exp $
//
// Library: Foundation
// Package: Core
// Module:  AutoPtr
//
// Definition of the AutoPtr template class.
//
// Copyright (c) 2004-2006, Applied Informatics Software Engineering GmbH.
// and Contributors.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//

#ifndef Foundation_AutoPtr_INCLUDED
#define Foundation_AutoPtr_INCLUDED

#include "Exception.h"
#include "Foundation.h"
#include <algorithm>

template <class C>
class CAutoPtr
/// AutoPtr is a "smart" pointer for classes implementing
/// reference counting based garbage collection.
/// To be usable with the AutoPtr template, a class must
/// implement the following behaviour:
/// A class must maintain a reference count.
/// The constructors of the object initialize the reference
/// count to one.
/// The class must implement a public duplicate() method:
///     void duplicate();
/// that increments the reference count by one.
/// The class must implement a public release() method:
///     void release()
/// that decrements the reference count by one, and,
/// if the reference count reaches zero, deletes the
/// object.
///
/// AutoPtr works in the following way:
/// If an AutoPtr is assigned an ordinary pointer to
/// an object (via the constructor or the assignment operator),
/// it takes ownership of the object and the object's reference
/// count remains unchanged.
/// If the AutoPtr is assigned another AutoPtr, the
/// object's reference count is incremented by one by
/// calling duplicate() on its object.
/// The destructor of AutoPtr calls release() on its
/// object.
/// AutoPtr supports dereferencing with both the ->
/// and the * operator. An attempt to dereference a null
/// AutoPtr results in a NullPointerException being thrown.
/// AutoPtr also implements all relational operators.
/// Note that AutoPtr allows casting of its encapsulated data types.
{
public:
  CAutoPtr() : _ptr(0) {}

  CAutoPtr(C *ptr) : _ptr(ptr) {}

  CAutoPtr(C *ptr, bool shared) : _ptr(ptr) {
    if (shared && _ptr)
      _ptr->duplicate();
  }

  CAutoPtr(const CAutoPtr &ptr) : _ptr(ptr._ptr) {
    if (_ptr)
      _ptr->duplicate();
  }

  template <class Other>
  CAutoPtr(const CAutoPtr<Other> &ptr) : _ptr(const_cast<Other *>(ptr.get())) {
    if (_ptr)
      _ptr->duplicate();
  }

  ~CAutoPtr() {
    if (_ptr)
      _ptr->release();
  }

  CAutoPtr &assign(C *ptr) {
    if (_ptr != ptr) {
      if (_ptr)
        _ptr->release();
      _ptr = ptr;
    }
    return *this;
  }

  CAutoPtr &assign(C *ptr, bool shared) {
    if (_ptr != ptr) {
      if (_ptr)
        _ptr->release();
      _ptr = ptr;
      if (shared && _ptr)
        _ptr->duplicate();
    }
    return *this;
  }

  CAutoPtr &assign(const CAutoPtr &ptr) {
    if (&ptr != this) {
      if (_ptr)
        _ptr->release();
      _ptr = ptr._ptr;
      if (_ptr)
        _ptr->duplicate();
    }
    return *this;
  }

  template <class Other> CAutoPtr &assign(const CAutoPtr<Other> &ptr) {
    if (ptr.get() != _ptr) {
      if (_ptr)
        _ptr->release();
      _ptr = const_cast<Other *>(ptr.get());
      if (_ptr)
        _ptr->duplicate();
    }
    return *this;
  }

  CAutoPtr &operator=(C *ptr) { return assign(ptr); }

  CAutoPtr &operator=(const CAutoPtr &ptr) { return assign(ptr); }

  template <class Other> CAutoPtr &operator=(const CAutoPtr<Other> &ptr) {
    return assign<Other>(ptr);
  }

  void swap(CAutoPtr &ptr) { std::swap(_ptr, ptr._ptr); }

  template <class Other>
  CAutoPtr<Other> cast() const
  /// Casts the AutoPtr via a dynamic cast to the given type.
  /// Returns an AutoPtr containing NULL if the cast fails.
  /// Example: (assume class Sub: public Super)
  ///    AutoPtr<Super> super(new Sub());
  ///    AutoPtr<Sub> sub = super.cast<Sub>();
  ///    poco_assert (sub.get());
  {
    Other *pOther = dynamic_cast<Other *>(_ptr);
    return CAutoPtr<Other>(pOther, true);
  }

  template <class Other>
  CAutoPtr<Other> unsafeCast() const
  /// Casts the AutoPtr via a static cast to the given type.
  /// Example: (assume class Sub: public Super)
  ///    AutoPtr<Super> super(new Sub());
  ///    AutoPtr<Sub> sub = super.unsafeCast<Sub>();
  ///    poco_assert (sub.get());
  {
    Other *pOther = static_cast<Other *>(_ptr);
    return CAutoPtr<Other>(pOther, true);
  }

  C *operator->() {
    if (_ptr)
      return _ptr;
    else
      throw CNullPointerException();
  }

  const C *operator->() const {
    if (_ptr)
      return _ptr;
    else
      throw CNullPointerException();
  }

  C &operator*() {
    if (_ptr)
      return *_ptr;
    else
      throw CNullPointerException();
  }

  const C &operator*() const {
    if (_ptr)
      return *_ptr;
    else
      throw CNullPointerException();
  }

  C *get() { return _ptr; }

  const C *get() const { return _ptr; }

  operator C *() { return _ptr; }

  operator const C *() const { return _ptr; }

  bool operator!() const { return _ptr == 0; }

  bool isNull() const { return _ptr == 0; }

  C *duplicate() {
    if (_ptr)
      _ptr->duplicate();
    return _ptr;
  }

  bool operator==(const CAutoPtr &ptr) const { return _ptr == ptr._ptr; }

  bool operator==(const C *ptr) const { return _ptr == ptr; }

  bool operator==(C *ptr) const { return _ptr == ptr; }

  bool operator!=(const CAutoPtr &ptr) const { return _ptr != ptr._ptr; }

  bool operator!=(const C *ptr) const { return _ptr != ptr; }

  bool operator!=(C *ptr) const { return _ptr != ptr; }

  bool operator<(const CAutoPtr &ptr) const { return _ptr < ptr._ptr; }

  bool operator<(const C *ptr) const { return _ptr < ptr; }

  bool operator<(C *ptr) const { return _ptr < ptr; }

  bool operator<=(const CAutoPtr &ptr) const { return _ptr <= ptr._ptr; }

  bool operator<=(const C *ptr) const { return _ptr <= ptr; }

  bool operator<=(C *ptr) const { return _ptr <= ptr; }

  bool operator>(const CAutoPtr &ptr) const { return _ptr > ptr._ptr; }

  bool operator>(const C *ptr) const { return _ptr > ptr; }

  bool operator>(C *ptr) const { return _ptr > ptr; }

  bool operator>=(const CAutoPtr &ptr) const { return _ptr >= ptr._ptr; }

  bool operator>=(const C *ptr) const { return _ptr >= ptr; }

  bool operator>=(C *ptr) const { return _ptr >= ptr; }

private:
  C *_ptr;
};

template <class C> inline void swap(CAutoPtr<C> &p1, CAutoPtr<C> &p2) {
  p1.swap(p2);
}

#endif // Foundation_AutoPtr_INCLUDED
