/* AXPbox Alpha Emulator
 * Copyright (C) 2020 Tomáš Glozar
 * Website: https://github.com/lenticularis39/axpbox
 *
 * Forked from: ES40 emulator
 * Copyright (C) 2007-2008 by the ES40 Emulator Project
 * Copyright (C) 2007 by Camiel Vanderhoeven
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
 * USA.
 *
 * Although this is not required, the author would appreciate being notified of,
 * and receiving any modifications you may make to the source code that might
 * serve the general public.
 *
 * Parts of this file based upon the Poco C++ Libraries, which is Copyright (C)
 * 2004-2006, Applied Informatics Software Engineering GmbH. and Contributors.
 */

//
// Mutex_POSIX.cpp
//
// $Id: Mutex_POSIX.cpp,v 1.1 2008/05/31 15:47:24 iamcamiel Exp $
//
// Library: Foundation
// Package: Threading
// Module:  Mutex
//
// Copyright (c) 2004-2008, Applied Informatics Software Engineering GmbH.
// and Contributors.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//

#include "Mutex_POSIX.hpp"
#include "Timestamp.hpp"
#if !defined(POCO_NO_SYS_SELECT_H)
#include <sys/select.h>
#endif
#include <sys/time.h>
#include <unistd.h>

#if defined(_POSIX_TIMEOUTS) && (_POSIX_TIMEOUTS - 200112L) >= 0L
#if defined(_POSIX_THREADS) && (_POSIX_THREADS - 200112L) >= 0L
#define POCO_HAVE_MUTEX_TIMEOUT
#endif
#endif

CMutexImpl::CMutexImpl() {
  pthread_mutexattr_t attr;
  pthread_mutexattr_init(&attr);
#if defined(PTHREAD_MUTEX_RECURSIVE_NP)
  pthread_mutexattr_settype_np(&attr, PTHREAD_MUTEX_RECURSIVE_NP);
#else
  pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
#endif
  if (pthread_mutex_init(&_mutex, &attr)) {
    pthread_mutexattr_destroy(&attr);
    throw CSystemException("cannot create mutex");
  }
  pthread_mutexattr_destroy(&attr);
}

CMutexImpl::CMutexImpl(bool fast) {
  pthread_mutexattr_t attr;
  pthread_mutexattr_init(&attr);
#if defined(PTHREAD_MUTEX_RECURSIVE_NP)
  pthread_mutexattr_settype_np(&attr, fast ? PTHREAD_MUTEX_NORMAL_NP
                                           : PTHREAD_MUTEX_RECURSIVE_NP);
#else
  pthread_mutexattr_settype(&attr, fast ? PTHREAD_MUTEX_NORMAL
                                        : PTHREAD_MUTEX_RECURSIVE);
#endif
  if (pthread_mutex_init(&_mutex, &attr)) {
    pthread_mutexattr_destroy(&attr);
    throw CSystemException("cannot create mutex");
  }
  pthread_mutexattr_destroy(&attr);
}

CMutexImpl::~CMutexImpl() { pthread_mutex_destroy(&_mutex); }

bool CMutexImpl::tryLockImpl(long milliseconds) {
#if defined(POCO_HAVE_MUTEX_TIMEOUT)
  struct timespec abstime;
  struct timeval tv;
  gettimeofday(&tv, NULL);
  abstime.tv_sec = tv.tv_sec + milliseconds / 1000;
  abstime.tv_nsec = tv.tv_usec * 1000 + (milliseconds % 1000) * 1000000;
  if (abstime.tv_nsec >= 1000000000) {
    abstime.tv_nsec -= 1000000000;
    abstime.tv_sec++;
  }
  int rc = pthread_mutex_timedlock(&_mutex, &abstime);
  if (rc == 0)
    return true;
  else if (rc == ETIMEDOUT)
    return false;
  else
    throw CSystemException("cannot lock mutex");
#else
  const int sleepMillis = 5;
  CTimestamp now;
  CTimestamp::TimeDiff diff(CTimestamp::TimeDiff(milliseconds) * 1000);
  do {
    int rc = pthread_mutex_trylock(&_mutex);
    if (rc == 0)
      return true;
    else if (rc != EBUSY)
      throw CSystemException("cannot lock mutex");
    struct timeval tv;
    tv.tv_sec = 0;
    tv.tv_usec = sleepMillis * 1000;
    select(0, NULL, NULL, NULL, &tv);
  } while (!now.isElapsed(diff));
  return false;
#endif
}

CFastMutexImpl::CFastMutexImpl() : CMutexImpl(true) {}

CFastMutexImpl::~CFastMutexImpl() {}
