/* ES40 emulator.
 * Copyright (C) 2007-2008 by the ES40 Emulator Project
 *
 * WWW    : http://www.es40.org
 * E-mail : camiel@es40.org
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
 * USA.
 *
 * Although this is not required, the author would appreciate being notified of,
 * and receiving any modifications you may make to the source code that might
 * serve the general public.
 *
 * Parts of this file based upon the Poco C++ Libraries, which is Copyright (C)
 * 2004-2006, Applied Informatics Software Engineering GmbH. and Contributors.
 */

/**
 * $Id: Thread_POSIX.cpp,v 1.1 2008/05/31 15:47:29 iamcamiel Exp $
 *
 * X-1.1        Camiel Vanderhoeven                             31-MAY-2008
 *      Initial version for ES40 emulator.
 **/

//
// Thread_POSIX.cpp
//
// $Id: Thread_POSIX.cpp,v 1.1 2008/05/31 15:47:29 iamcamiel Exp $
//
// Library: Foundation
// Package: Threading
// Module:  Thread
//
// Copyright (c) 2004-2007, Applied Informatics Software Engineering GmbH.
// and Contributors.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//

#include "Thread_POSIX.h"
#include "Exception.h"
#include <signal.h>

//
// Block SIGPIPE in main thread.
//
#if defined(POCO_OS_FAMILY_UNIX)
class CSignalBlocker {
public:
  CSignalBlocker() {
    sigset_t sset;
    sigemptyset(&sset);
    sigaddset(&sset, SIGPIPE);
    pthread_sigmask(SIG_BLOCK, &sset, 0);
  }
  ~CSignalBlocker() {}
};

static CSignalBlocker signalBlocker;
#endif

pthread_key_t CThreadImpl::_currentKey;
bool CThreadImpl::_haveCurrentKey = false;

CThreadImpl::CThreadImpl() : _pData(new CThreadData) {
  if (!_haveCurrentKey) {
    if (pthread_key_create(&_currentKey, NULL))
      throw CSystemException("cannot allocate thread context key");
    _haveCurrentKey = true;
  }
}

CThreadImpl::~CThreadImpl() {
  if (_pData->pTarget)
    pthread_detach(_pData->thread);
}

void CThreadImpl::setPriorityImpl(int prio) {
  if (prio != _pData->prio) {
    _pData->prio = prio;
    if (_pData->pTarget) {
      struct sched_param par;
      par.sched_priority = mapPrio(_pData->prio);
      if (pthread_setschedparam(_pData->thread, SCHED_OTHER, &par))
        throw CSystemException("cannot set thread priority");
    }
  }
}

void CThreadImpl::startImpl(CRunnable &target) {
  if (_pData->pTarget)
    throw CSystemException("thread already running");

  _pData->pTarget = &target;
  if (pthread_create(&_pData->thread, NULL, entry, this)) {
    _pData->pTarget = 0;
    throw CSystemException("cannot start thread");
  }

  if (_pData->prio != PRIO_NORMAL_IMPL) {
    struct sched_param par;
    par.sched_priority = mapPrio(_pData->prio);
    if (pthread_setschedparam(_pData->thread, SCHED_OTHER, &par))
      throw CSystemException("cannot set thread priority");
  }
}

void CThreadImpl::joinImpl() {
  _pData->done.wait();
  void *result;
  if (pthread_join(_pData->thread, &result))
    throw CSystemException("cannot join thread");
}

bool CThreadImpl::joinImpl(long milliseconds) {
  if (_pData->done.tryWait(milliseconds)) {
    void *result;
    if (pthread_join(_pData->thread, &result))
      throw CSystemException("cannot join thread");
    return true;
  } else
    return false;
}

bool CThreadImpl::isRunningImpl() const { return _pData->pTarget != 0; }

CThreadImpl *CThreadImpl::currentImpl() {
  if (_haveCurrentKey)
    return reinterpret_cast<CThreadImpl *>(pthread_getspecific(_currentKey));
  else
    return 0;
}

void *CThreadImpl::entry(void *pThread) {
  pthread_setspecific(_currentKey, pThread);

#if defined(POCO_OS_FAMILY_UNIX)
  sigset_t sset;
  sigemptyset(&sset);
  sigaddset(&sset, SIGQUIT);
  sigaddset(&sset, SIGTERM);
  sigaddset(&sset, SIGPIPE);
  pthread_sigmask(SIG_BLOCK, &sset, 0);
#endif

  CThreadImpl *pThreadImpl = reinterpret_cast<CThreadImpl *>(pThread);
  std::shared_ptr<CThreadData> pData = pThreadImpl->_pData;
  try {
    pData->pTarget->run();
  } catch (CException &exc) {
    printf("Thread has terminated with an unexpected %s exception:\n",
           exc.className());
    printf("  %s\n", exc.displayText().c_str());
  } catch (std::exception &exc) {
    printf("Thread has terminated with an unexpected %s exception.\n",
           exc.what());
  } catch (...) {
    printf("Thread has terminated with an unexpected exception.\n");
  }
  pData->pTarget = 0;
  pData->done.set();
  return 0;
}

int CThreadImpl::mapPrio(int prio) {
#if defined(__VMS) || defined(__digital__)
  static const int pmin = PRI_OTHER_MIN;
  static const int pmax = PRI_OTHER_MAX;
#else
  static const int pmin = sched_get_priority_min(SCHED_OTHER);
  static const int pmax = sched_get_priority_max(SCHED_OTHER);
#endif

  switch (prio) {
  case PRIO_LOWEST_IMPL:
    return pmin;
  case PRIO_LOW_IMPL:
    return pmin + (pmax - pmin) / 4;
  case PRIO_HIGH_IMPL:
    return pmin + 3 * (pmax - pmin) / 4;
  case PRIO_HIGHEST_IMPL:
    return pmax;
  case PRIO_NORMAL_IMPL:
  default:
    return pmin + (pmax - pmin) / 2;
  }
  return -1; // just to satisfy compiler - we'll never get here anyway
}
